spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/"
    username: postgres
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
