name: Docker

on:
  push:
    branches:
      - main

permissions:
  packages: write

env:
  IMAGE_NAME: ghcr.io/clubmanager1999/backend:latest

jobs:
  push:
    name: Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: ./gradlew bootBuildImage --imageName=$IMAGE_NAME
      - name: Push
        run: docker push $IMAGE_NAME
